hwdec=nvdec-copy
vo=gpu
volume=100
volume-max=200
save-position-on-quit
keep-open=yes
fullscreen=no
ytdl-format=bestvideo[height=1080][vcodec^=avc1]+bestaudio/bestvideo[height=720][vcodec^=avc1]+bestaudio/best[height<=1080]
ytdl-raw-options='sub-langs="en,en-US,ru,ru-RU",write-subs=,write-auto-subs='
save-watch-history=yes
osd-font="JetBrainsMono Nerd Font Propo"
osd-color='#FFc0caf5'
osd-border-color='#FF16161e'
